### ISSUE TITLE
Make datasets more consistent

### ISSUE THREAD

**Issue by StevenMMortimer** [bradleyboehmke/completejourney#7]
@bradleyboehmke Jeff and I were talking about ways to standardize the data so that users find it easier to navigate. E.g. Changing `household_key` to `household_id` since every other id column ends in `_id`. Changing `campaign_table` as the dataset name to `campaigns` to match the plural entity names like `transactions`, `products`, `coupons`. 

Here was the list we could think of: 
 - Save dataset as tibbles
 - Make dataset names consistent (e.g. households, campaigns)
 - Make the `key` vs. `id` suffixes consistent (household_key vs. store_id)
 - Reorder columns (id cols first, all other, then timestamps last)

We can remake the ER diagram or other collateral if needed. I think this can be a last step after you know you've got the right data here on GitHub.

**Comment by bradleyboehmke** [comment]
@StevenMMortimer Go ahead and check out the updates.  I've updated the data sets to align to your comments above.  The data sets are now named:

- `transactions`: products purchased by households
- `products`: product metadata (brand, description, etc.)
- `demographics`: household demographic data (age, income, family size, etc.)
- `campaigns`: campaigns received by each household
- `campaign_descriptions`: campaign metadata (length of time active)
- `coupons`: coupon metadata (UPC code, campaign, etc.)
- `coupon_redemptions`: coupon redemptions (household, day, UPC code, campaign)
- `product_placements`: product placement in mailers and in stores corresponding to advertising campaigns

If you think they are consistent enough then we can go ahead and revamp some of the diagrams and wrap up the vignette.

**Comment by jeffboichuk** [comment]
Thanks, @StevenMMortimer. @bradleyboehmke, your updates look great. What do you think about `trade_promotions` as an alternative name for the  `product_placements` data set? 

@jonathan-eman and I built out a [Google Sheet](https://docs.google.com/spreadsheets/d/1SMqCuKl-AYRE7vUqPTuaVjfrwKJvEX2jcc-GGTLU3K4/edit?usp=sharing) that he created. I think it can serve as a to-do list of sorts for changes related to consistency.

**Comment by bradleyboehmke** [comment]
Alright @StevenMMortimer and @jeffboichuk .  First, I apologize for being so late on this; got bogged down with other tasks and dropped the ball.  

Today I updated all data sets and carried over what @StevenMMortimer did in the private repo.  You can see the code that transforms the original, downloaded data to its current form in the package [here](https://github.com/bradleyboehmke/completejourney/blob/master/data-raw/prep-data.R).

The changes largely align with what was on the Google sheet with minor differences:

- I did not change `product$brand` to `product$private_label`.  Mainly because `product$private_label` should act more as a dummy variable (0/1) whereas the name brand signals their are more than one option for the brand type.
- I changed `promotions$mailer` to `promotions$mailer_location` rather than `feature_location` because I thought it was more consistent with the true meaning of the variable.
- I changed `coupon_redemptions$day` to `coupon_redemptions$redemption_date` rather than just `date` to make it less generic (I rarely use "date" as a name due to its abstractness).
- Also, I removed the `campaigns$description` so the `campaigns` data set only has `campaign_id` and `household_id` (the `description` variable was non-informative since that variable is available from the `campaign_descriptions` data. 

Otherwise, most of the other changes should be good to go.  The package is quite a bit lighter since we reduced the observations down to 2017 only so hopefully that will help with our CRAN submission.

Let me know your thoughts.  I still haven't worked on the vignette as I want to get the data consistency down.  If you all are satisfied I can wrap up the vignette and prepare for submission.

**Comment by StevenMMortimer** [comment]
@bradleyboehmke Thanks! Great stuff. Really appreciate you getting your hands dirty on this. 

We're still making some changes to the data. We found some inconsistencies between household composition, kids count, and household size that should be reconciled. We are going to upsample or split records between the customers to get the total count back up to 2500. After cutting the data to one year we are 31 customers shy of the 2500 number.

We're thinking that we will be done towards the end of next week. We'll put in a pull request to update your script and ask you to run it once more. 

All your changes make sense. Just a comment on the first bullet: We thought `product$brand` was a dummy variable since it only takes two values `National` or `Private`. Is that not the case or is there another reason to stick with `brand`?

@jeffboichuk might have some thoughts as well.

**Comment by bradleyboehmke** [comment]
Sounds good.  

Re: `product$brand` - to rename `product$brand` as `product$private_label`, I would expect all the values in this column to be 0 or 1 to indicate if the product was or was not a private label brand.  Think about it like a gender variable which has values male or female - renaming to `product$private_label` would be synonymous to renaming `gender` to male.  You want to make sure the name of the variable is different then one of variables categories.

**Comment by StevenMMortimer** [comment]
@bradleyboehmke Sorry for the months of delay, but I finally got around to folding in some logic to reconcile the household composition and kids count along with finishing up the vignette and other little details. That's all wrapped up in PR #9. Let me know if there's anything else I can do. I think this is good to go to CRAN whenever you feel it's ready for that. We can't thank you enough for working on this.
